language: java

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2

after_success:
  - ./deploy.sh
 
env:
  global:
    - GH_ACCOUNT=dualuse
    - GH_REPOSITORY=maven
    - secure: "ZjUV/A+XMhqPXrDQGSzAXaVO+ZDla+7/JqIfeV1mVJPt6j9qfYCV06UYAuOh7nGwByEKpbmicuIivRlaCLz/mayzIggT8hwSgdhknMiBNZaCX3L0J0QoaiBs4ehX/7egYY02OxoonpKGs2ByDh40Ydibm5It96Mq1Ps8XN+7YQFEOyQOUQk/SUMwN4c6FBY8Stv0fPSMHPBTsvNkBLLWFy+wIkdJzhZi4zmq+pvnpgUN9eIeuS4HUK0mIyaFJt4JnNJB5YkO8aO+f7mtE9vFWvUfTxdgWP5mJAyitUWLyezIUR/woyDLZFERR8zYfrO/QIaHA0XenrStkY6+OEA4GXywgLreCv6yAdjlDePOtS8pCjsdfDXWnXazZiTveXCamr1C6t2iyJQnSfrCn7P362JiQAyh7OxPGDC6oMqY2XUgh3PX//WEteNCglROjdgShLXqj3FiQPRJaU6Dh5gRjuw2Pm4rc7XqChQd5A4VNO9r2nTdulnxdEEbSWp5NdMeWQ+lrpnIrwUQittm8S18MFuuW0bqQTATQFBAXxcHJP6VQGsHEtgbFLfFrsm0AkkCR1tGk4xc5c3Sh49ZxGIa8QKld93hzifau30lRqwbY17cG8Ssihhgg0FRWY4wDyDJ20d0PSbeak8echlW2//X+J1kzyb9r3wX3JBJ/bA+gOo="
